name: recipe-finder
  github:
    branch: main
    deploy_on_push: true
    repo: ashleygrobler04/recipe-finder
  name: recipe-finder
  health_check:
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 2
      failure_threshold: 3
      http_path: /
      port: 5090